"""add_missing_columns

Revision ID: 06957b386a71
Revises: 622d3840ed62
Create Date: 2026-04-17 01:27:59.340268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06957b386a71'
down_revision: Union[str, Sequence[str], None] = '622d3840ed62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.alter_column('warehouses', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="created_at::timestamp with time zone")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warehouses', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('warehouses', 'branch_id')
    # ### end Alembic commands ###