"""auto update

Revision ID: 611a16d29f3f
Revises: 69c73145c159
Create Date: 2026-04-15 03:12:08.292980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611a16d29f3f'
down_revision: Union[str, Sequence[str], None] = '69c73145c159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receiving_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receiving_document_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expected_quantity', sa.Float(), nullable=True),
    sa.Column('received_quantity', sa.Float(), nullable=True),
    sa.Column('lot_number', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.String(), nullable=True),
    sa.Column('qc_status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receiving_lines_id'), 'receiving_lines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receiving_lines_id'), table_name='receiving_lines')
    op.drop_table('receiving_lines')
    # ### end Alembic commands ###